### ISSUE TITLE
NPE using version inheritance on parent-children projects

### ISSUE THREAD

**Issue by cdelmas** [smartcodeltd/release-candidate-maven-plugin#1]
Trying to update the version of a parent project, using version inheritance in child projects, make the plugin fail with an NPE at com.smartcodeltd.UpdateVersionMojo.update(UpdateVersionMojo.java:145).

Reproduced on the given project with Maven 3.3.9.

Problem: The code expects to find a version tag which doesn't exist.

Workaround: add a version tag in each module.

Possible fix: if no version tag found, try to update the parent version (which is inherited).

[issue.zip](https://github.com/smartcodeltd/release-candidate-maven-plugin/files/78412/issue.zip)

**Comment by jan-molak** [comment]
Should be fixed in the latest build. Many thanks for attaching the test `pom`s, it really helped with investigating the issue :smiley: 

I allowed myself to add your example to [the integration tests package](https://github.com/smartcodeltd/release-candidate-maven-plugin/tree/74e0d3bdc459a27bd29f98234891a48746b67ba6/src/it).

Best,
Jan
