### ISSUE TITLE
Update version in parent-child projects doesn't update the parent version.

### ISSUE THREAD

**Issue by cdelmas** [smartcodeltd/release-candidate-maven-plugin#2]
When updating the version of a parent project with version tags in child projects' pom, the parent version is not updated to the new version (while the project's version is).

Note: This is not the same issue than #1.
[issue.zip](https://github.com/smartcodeltd/release-candidate-maven-plugin/files/78422/issue.zip)

**Comment by jan-molak** [comment]
Should be fixed in the latest build. Again, thanks for attaching the test `pom`s, it really helped with investigating the issue :smiley: 

Your example is now part of [the integration tests package](https://github.com/smartcodeltd/release-candidate-maven-plugin/tree/74e0d3bdc459a27bd29f98234891a48746b67ba6/src/it).

Best,
Jan
