### ISSUE TITLE
Parent POM's version of submodule is not updated when run against release version

### ISSUE THREAD

**Issue by janzyka** [smartcodeltd/release-candidate-maven-plugin#8]
In my CI it may happen that the plugin runs agains project which has release version, like `1.0.0`. My parent pom is changed as per the `releaseVersionFormat` where my submodules still refer to parent version `1.0.0`.

**Comment by jan-molak** [comment]
Hi and thanks for the feedback @janzyka. Would you mind raising a PR with example poms so that I can reproduce the issue?

Have a look at the [existing integration tests](https://github.com/smartcodeltd/release-candidate-maven-plugin/tree/master/src/it/) and just add one that covers this scenario please.

Many thanks for your time and help.
Jan

**Comment by janzyka** [comment]
On pull request.
